language: node_js
node_js:
  - 4
before_script:
  - ./node_modules/.bin/typings i
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run browser
  - npm test
after_success:
  - npm run coverage
